using System;
using System.Collections.Generic;

namespace OutlookAiHelper.Localization
{
    public enum UiLanguage
    {
        ZhTw,
        ZhCn,
        EnUs
    }

    public static class Strings
    {
        private static UiLanguage _language = UiLanguage.ZhTw;

        public static UiLanguage Language
        {
            get { return _language; }
            set { _language = value; }
        }

        public static string T(string key)
        {
            var table = Current();
            string value;
            if (table.TryGetValue(key, out value))
            {
                return value;
            }

            return key;
        }

        public static string QuadrantName(Core.Classification.Quadrant q)
        {
            switch (q)
            {
                case Core.Classification.Quadrant.Q1UrgentImportant:
                    return T("quadrant.q1");
                case Core.Classification.Quadrant.Q2UrgentNotImportant:
                    return T("quadrant.q2");
                case Core.Classification.Quadrant.Q3ImportantNotUrgent:
                    return T("quadrant.q3");
                default:
                    return T("quadrant.q4");
            }
        }

        private static Dictionary<string, string> Current()
        {
            if (_language == UiLanguage.EnUs)
            {
                return En;
            }

            if (_language == UiLanguage.ZhCn)
            {
                return ZhCn;
            }

            return ZhTw;
        }

        private static readonly Dictionary<string, string> ZhTw = new Dictionary<string, string>
        {
            { "app.title", "Outlook 分類助手" },
            { "nav.quadrants", "Outlook 郵件清單" },
            { "nav.todo", "待回待辦" },
            { "nav.settings", "設定" },
            { "nav.sidebarToggle", "顯示/隱藏側邊欄" },
            { "scope.days", "天數" },
            { "action.scan", "開始掃描" },
            { "action.cancel", "取消" },
            { "action.reclassify", "改到其他象限" },
            { "action.retry", "重試" },
            { "action.addTodo", "加入待辦" },
            { "action.openInOutlook", "在 Outlook 開啟" },
            { "action.addTodoManual", "新增待辦" },
            { "action.todoDone", "完成" },
            { "action.todoReopen", "重開" },
            { "action.todoDelete", "刪除" },
            { "filter.all", "全部" },
            { "quadrant.q1", "緊急重要" },
            { "quadrant.q2", "緊急不重要" },
            { "quadrant.q3", "重要不緊急" },
            { "quadrant.q4", "不重要不緊急" },
            { "reason.title", "為什麼在這裡" },
            { "reason.override.manual", "你手動指定的象限" },
            { "reason.keyword.urgent", "標題含緊急詞" },
            { "reason.keyword.important", "標題含重要詞" },
            { "reason.signal.meeting", "會議邀請" },
            { "reason.signal.unread", "尚未讀取" },
            { "reason.signal.flag", "有旗標" },
            { "reason.signal.importance", "寄件者標為高重要性" },
            { "reason.signal.vip", "VIP 寄件者" },
            { "reason.signal.default", "沒有特殊訊號" },
            { "empty.title", "這個範圍沒有郵件" },
            { "empty.body", "調整天數或先執行掃描。" },
            { "empty.start", "開始掃描" },
            { "loading.scanning", "正在掃描郵件…" },
            { "error.title", "無法完成" },
            { "error.outlook.unavailable", "未偵測到 Outlook，請先開啟 Outlook 後再掃描。" },
            { "error.outlook.not_detected", "未偵測到 Outlook，請先開啟 Outlook 後再掃描。" },
            { "error.scan.failed", "無法讀取郵件，已中止本次掃描。可縮小範圍後重試。" },
            { "error.blank.prevented", "已阻止空白畫面，請重試或開啟設定。" },
            { "status.readonly", "唯讀模式：不會修改任何郵件" },
            { "status.done", "掃描完成：{0} 封" },
            { "status.cancelled", "已取消掃描" },
            { "detail.subject", "主旨" },
            { "detail.from", "寄件者" },
            { "detail.time", "時間" },
            { "detail.folder", "資料夾" },
            { "pick.quadrant", "選擇象限" },
            { "todo.title", "待回待辦" },
            { "todo.filter.open", "待處理" },
            { "todo.filter.done", "已完成" },
            { "todo.filter.all", "全部" },
            { "todo.filter.label", "待辦狀態" },
            { "todo.toggleDone", "標記完成：{0}" },
            { "todo.toggleDone.help", "勾選或取消勾選這一列待辦事項" },
            { "todo.empty.title", "沒有待辦" },
            { "todo.empty.body", "從郵件加入待辦，或手動新增一條。" },
            { "todo.add.hint", "輸入待辦後按 Enter" },
            { "todo.added", "已加入待辦" },
            { "todo.source", "來自：{0}" },
            { "todo.detail.state", "狀態" },
            { "todo.detail.quadrant", "象限" },
            { "todo.detail.created", "建立時間" },
            { "todo.detail.updated", "更新時間" },
            { "todo.detail.due", "到期" },
            { "todo.detail.note", "備註" },
            { "todo.detail.mailMissing", "這封郵件不在目前的掃描範圍內，僅顯示待辦記錄的資訊。" },
            { "todo.waiting", "等待 {0} 天" },
            { "todo.waiting.today", "今天加入" },
            { "todo.overdue", "逾期 {0} 天" },
            { "todo.due.today", "今天到期" },
            { "todo.due.in", "{0} 天後到期" },
            { "todo.due.none", "未設定到期日" },
            { "todo.action.openMail", "開啟原信" },
            { "todo.action.setDue", "設定到期日" },
            { "todo.action.clearDue", "清除到期日" },
            { "todo.action.clearDone", "清除已完成" },
            { "todo.cleared", "已清除 {0} 筆已完成待辦" },
            { "todo.note.placeholder", "輸入備註…" },
            { "todo.note.save", "儲存備註" },
            { "todo.note.saved", "備註已儲存" },
            { "todo.sort", "排序" },
            { "todo.sort.waiting", "等待最久" },
            { "todo.sort.due", "到期日" },
            { "todo.sort.quadrant", "象限" },
            { "todo.sort.updated", "最近更新" },
            { "todo.sort.manual", "加入順序" },
            { "todo.clearDone.confirm", "將永久刪除 {0} 筆已完成的待回待辦，此動作無法復原。" },
            { "settings.days", "預設掃描天數" },
            { "settings.scanScope", "掃描一律排除「刪除的郵件」與「垃圾郵件」（含其子資料夾）。" },
            { "settings.autoRefresh", "自動偵測新郵件" },
            { "settings.autoRefresh.off", "關閉" },
            { "settings.autoRefresh.minutes", "{0} 分鐘" },
            { "auto.refresh.updated", "自動更新：{0} 封" },
            { "settings.language", "介面語言" },
            { "settings.urgentKeywords", "緊急關鍵詞（逗號分隔）" },
            { "settings.importantKeywords", "重要關鍵詞（逗號分隔）" },
            { "settings.vip", "VIP 寄件者（逗號分隔）" },
            { "settings.save", "儲存設定" },
            { "settings.saved", "設定已儲存" },
            { "settings.language.needRestart", "語言已變更，需要重開程式才會完整生效。" },
            { "settings.restart.auto", "立即重開" },
            { "settings.restart.manual", "我稍後手動重開" },
            { "settings.restart.later", "下次重開再生效" },
            { "settings.restart.title", "套用語言變更" },
            { "privacy.title", "隱私與資料" },
            { "privacy.location", "資料位置" },
            { "privacy.minimize", "只處理本機郵件欄位；信件內文預設不落盤。" },
            { "privacy.export", "匯出本地資料" },
            { "privacy.exported", "已匯出到：" },
            { "privacy.openFolder", "開啟資料夾" },
            { "privacy.clear", "清除本地資料" },
            { "privacy.clear.confirm", "確定清除設定、待辦與分類記憶？此動作無法復原。" },
            { "privacy.cleared", "本地資料已清除" },
            { "privacy.ai.off", "AI 未啟用（增強層，不影響核心分類）" },
            { "restart.title", "需要重開程式" },
            { "restart.body", "部分設定要重開程式才會完整生效。" },
            { "restart.now", "立即重開" },
            { "restart.later", "手動重開" },
            { "restart.next", "下次重開生效" },
            { "auto.scan.start", "依上次設定自動掃描…" },
            { "ai.title", "AI 增強（選擇性）" },
            { "ai.providers", "AI 供應商" },
            { "ai.provider", "供應商" },
            { "ai.addProvider", "新增" },
            { "ai.removeProvider", "刪除" },
            { "ai.loadModels", "載入模型" },
            { "ai.models", "模型" },
            { "ai.models.empty", "先輸入地址與 Key，再載入模型" },
            { "ai.models.loaded", "已載入 {0} 個模型" },
            { "ai.models.failed", "無法取得模型列表" },

            { "ai.enabled", "啟用 AI" },
            { "ai.baseUrl", "Provider URL（OpenAI 相容）" },
            { "ai.model", "Model" },
            { "ai.apiKey", "API Key（僅存本機）" },
            { "ai.consent.title", "確認送出欄位" },
            { "ai.consent.body", "將只送出下列白名單欄位，不含信件內文。" },
            { "ai.consent.send", "確認送出" },
            { "ai.consent.cancel", "取消" },
            { "ai.action", "AI 說明" },
            { "ai.disabled", "AI 未啟用，核心功能不受影響。" },
            { "ai.network_failed", "AI 連線失敗，核心功能不受影響。" },
            { "ai.timeout", "AI 逾時，核心功能不受影響。" },
            { "ai.failed", "AI 無法完成，核心功能不受影響。" },
            { "ai.empty_response", "AI 沒有回傳內容。" },
            { "ai.bad_request", "AI 請求內容無效。" },
            { "ai.key.local", "金鑰只會寫入本機設定檔，不會寫入 Log。" },
            { "update.section", "軟體更新" },
            { "update.current", "目前版本" },
            { "update.check", "檢查更新" },
            { "update.checking", "正在檢查更新…" },
            { "update.upToDate", "已是最新版本" },
            { "update.upToDate.body", "目前版本 {0} 已是最新版本。" },
            { "update.none.title", "尚未發布版本" },
            { "update.none", "GitHub 上還沒有發布任何版本。" },
            { "update.available.short", "有新版本 {0}" },
            { "update.autostart", "啟動時自動檢查更新" },
            { "update.title.available", "有新版本可用" },
            { "update.body.available", "目前版本 {0}，最新版本 {1}。是否下載並更新？" },
            { "update.notes", "版本說明" },
            { "update.source", "來源" },
            { "update.file", "檔案" },
            { "update.size", "大小" },
            { "update.size.unknown", "未知" },
            { "update.install", "下載並更新" },
            { "update.later", "稍後" },
            { "update.page", "開啟下載頁面" },
            { "update.ok", "好" },
            { "update.downloading.title", "正在下載更新" },
            { "update.downloading.body", "下載期間請保持網路連線，完成後會詢問是否立即重新啟動。" },
            { "update.downloading.status", "準備中…" },
            { "update.ready.title", "更新已就緒" },
            { "update.ready.body", "已下載 {0}。重新啟動後即完成更新。" },
            { "update.restart.now", "立即重新啟動" },
            { "update.restart.later", "稍後由我重新啟動" },
            { "update.failed.title", "無法完成更新" },
            { "update.security", "更新檔僅從官方 GitHub Release 下載，連線使用 HTTPS，並比對來源白名單。" },
            { "update.prerelease", "預覽版" },
            { "update.error.network", "無法連線至 GitHub，請確認網路後再試。" },
            { "update.error.timeout", "連線逾時，請稍後再試。" },
            { "update.error.badRelease", "版本資訊格式無法解讀，已中止。" },
            { "update.error.untrusted", "下載來源未通過安全檢查，已中止。" },
            { "update.error.tooLarge", "更新檔案超過大小上限，已中止。" },
            { "update.error.incomplete", "下載的檔案不完整，已中止。" },
            { "update.error.size", "下載檔案大小與版本資訊不符，已中止。" },
            { "update.error.download", "下載更新失敗。" },
            { "update.error.locate", "找不到目前程式位置。" },
            { "update.error.unsupportedPath", "程式路徑含有不支援的字元，請改由下載頁面更新。" },
            { "update.error.readonly", "程式所在資料夾無法寫入，請改由下載頁面更新。" },
            { "update.error.config", "版本來源設定無效。" },
            { "update.error.policy", "更新來源未通過白名單檢查。" }
        };

        private static readonly Dictionary<string, string> ZhCn = new Dictionary<string, string>
        {
            { "app.title", "Outlook 分类助手" },
            { "nav.quadrants", "Outlook 邮件清单" },
            { "nav.todo", "待回待办" },
            { "nav.settings", "设置" },
            { "nav.sidebarToggle", "显示/隐藏侧边栏" },
            { "scope.days", "天数" },
            { "action.scan", "开始扫描" },
            { "action.cancel", "取消" },
            { "action.reclassify", "改到其他象限" },
            { "action.retry", "重试" },
            { "action.addTodo", "加入待办" },
            { "action.openInOutlook", "在 Outlook 打开" },
            { "action.addTodoManual", "新增待办" },
            { "action.todoDone", "完成" },
            { "action.todoReopen", "重开" },
            { "action.todoDelete", "删除" },
            { "filter.all", "全部" },
            { "quadrant.q1", "紧急重要" },
            { "quadrant.q2", "紧急不重要" },
            { "quadrant.q3", "重要不紧急" },
            { "quadrant.q4", "不重要不紧急" },
            { "reason.title", "为什么在这里" },
            { "reason.override.manual", "你手动指定的象限" },
            { "reason.keyword.urgent", "标题含紧急词" },
            { "reason.keyword.important", "标题含重要词" },
            { "reason.signal.meeting", "会议邀请" },
            { "reason.signal.unread", "尚未读取" },
            { "reason.signal.flag", "有旗标" },
            { "reason.signal.importance", "发件人标为高重要性" },
            { "reason.signal.vip", "VIP 发件人" },
            { "reason.signal.default", "没有特殊信号" },
            { "empty.title", "这个范围没有邮件" },
            { "empty.body", "调整天数或先执行扫描。" },
            { "empty.start", "开始扫描" },
            { "loading.scanning", "正在扫描邮件…" },
            { "error.title", "无法完成" },
            { "error.outlook.unavailable", "未侦测到 Outlook，请先打开 Outlook 后再扫描。" },
            { "error.outlook.not_detected", "未侦测到 Outlook，请先打开 Outlook 后再扫描。" },
            { "error.scan.failed", "无法读取邮件，已中止本次扫描。可缩小范围后重试。" },
            { "error.blank.prevented", "已阻止空白画面，请重试或打开设置。" },
            { "status.readonly", "只读模式：不会修改任何邮件" },
            { "status.done", "扫描完成：{0} 封" },
            { "status.cancelled", "已取消扫描" },
            { "detail.subject", "主题" },
            { "detail.from", "发件人" },
            { "detail.time", "时间" },
            { "detail.folder", "文件夹" },
            { "pick.quadrant", "选择象限" },
            { "todo.title", "待回待办" },
            { "todo.filter.open", "待处理" },
            { "todo.filter.done", "已完成" },
            { "todo.filter.all", "全部" },
            { "todo.filter.label", "待办状态" },
            { "todo.toggleDone", "标记完成：{0}" },
            { "todo.toggleDone.help", "勾选或取消勾选这一列待办事项" },
            { "todo.empty.title", "没有待办" },
            { "todo.empty.body", "从邮件加入待办，或手动新增一条。" },
            { "todo.add.hint", "输入待办后按 Enter" },
            { "todo.added", "已加入待办" },
            { "todo.source", "来自：{0}" },
            { "todo.detail.state", "状态" },
            { "todo.detail.quadrant", "象限" },
            { "todo.detail.created", "创建时间" },
            { "todo.detail.updated", "更新时间" },
            { "todo.detail.due", "到期" },
            { "todo.detail.note", "备注" },
            { "todo.detail.mailMissing", "这封邮件不在当前扫描范围内，仅显示待办记录的信息。" },
            { "todo.waiting", "等待 {0} 天" },
            { "todo.waiting.today", "今天加入" },
            { "todo.overdue", "逾期 {0} 天" },
            { "todo.due.today", "今天到期" },
            { "todo.due.in", "{0} 天后到期" },
            { "todo.due.none", "未设置到期日" },
            { "todo.action.openMail", "打开原邮件" },
            { "todo.action.setDue", "设置到期日" },
            { "todo.action.clearDue", "清除到期日" },
            { "todo.action.clearDone", "清除已完成" },
            { "todo.cleared", "已清除 {0} 条已完成待办" },
            { "todo.note.placeholder", "输入备注…" },
            { "todo.note.save", "保存备注" },
            { "todo.note.saved", "备注已保存" },
            { "todo.sort", "排序" },
            { "todo.sort.waiting", "等待最久" },
            { "todo.sort.due", "到期日" },
            { "todo.sort.quadrant", "象限" },
            { "todo.sort.updated", "最近更新" },
            { "todo.sort.manual", "加入顺序" },
            { "todo.clearDone.confirm", "将永久删除 {0} 条已完成的待回待办，此操作无法撤销。" },
            { "settings.days", "默认扫描天数" },
            { "settings.scanScope", "扫描一律排除「已删除邮件」与「垃圾邮件」（含其子文件夹）。" },
            { "settings.autoRefresh", "自动检测新邮件" },
            { "settings.autoRefresh.off", "关闭" },
            { "settings.autoRefresh.minutes", "{0} 分钟" },
            { "auto.refresh.updated", "自动更新：{0} 封" },
            { "settings.language", "界面语言" },
            { "settings.urgentKeywords", "紧急关键词（逗号分隔）" },
            { "settings.importantKeywords", "重要关键词（逗号分隔）" },
            { "settings.vip", "VIP 发件人（逗号分隔）" },
            { "settings.save", "保存设置" },
            { "settings.saved", "设置已保存" },
            { "settings.language.needRestart", "语言已更改，需要重启程序才会完整生效。" },
            { "settings.restart.auto", "立即重启" },
            { "settings.restart.manual", "我稍后手动重启" },
            { "settings.restart.later", "下次重启再生效" },
            { "settings.restart.title", "应用语言变更" },
            { "privacy.title", "隐私与数据" },
            { "privacy.location", "数据位置" },
            { "privacy.minimize", "只处理本机邮件字段；正文默认不落盘。" },
            { "privacy.export", "导出本地数据" },
            { "privacy.exported", "已导出到：" },
            { "privacy.openFolder", "打开文件夹" },
            { "privacy.clear", "清除本地数据" },
            { "privacy.clear.confirm", "确定清除设置、待办与分类记忆？此操作无法撤销。" },
            { "privacy.cleared", "本地数据已清除" },
            { "privacy.ai.off", "AI 未启用（增强层，不影响核心分类）" },
            { "restart.title", "需要重启程序" },
            { "restart.body", "部分设置要重启程序才会完整生效。" },
            { "restart.now", "立即重启" },
            { "restart.later", "手动重启" },
            { "restart.next", "下次重启生效" },
            { "auto.scan.start", "按上次设置自动扫描…" },
            { "ai.title", "AI 增强（可选）" },
            { "ai.providers", "AI 供应商" },
            { "ai.provider", "供应商" },
            { "ai.addProvider", "新增" },
            { "ai.removeProvider", "删除" },
            { "ai.loadModels", "加载模型" },
            { "ai.models", "模型" },
            { "ai.models.empty", "先输入地址与 Key，再加载模型" },
            { "ai.models.loaded", "已加载 {0} 个模型" },
            { "ai.models.failed", "无法获取模型列表" },

            { "ai.enabled", "启用 AI" },
            { "ai.baseUrl", "Provider URL（OpenAI 兼容）" },
            { "ai.model", "Model" },
            { "ai.apiKey", "API Key（仅存本机）" },
            { "ai.consent.title", "确认发送字段" },
            { "ai.consent.body", "只发送下列白名单字段，不含正文。" },
            { "ai.consent.send", "确认发送" },
            { "ai.consent.cancel", "取消" },
            { "ai.action", "AI 说明" },
            { "ai.disabled", "AI 未启用，核心功能不受影响。" },
            { "ai.network_failed", "AI 连接失败，核心功能不受影响。" },
            { "ai.timeout", "AI 超时，核心功能不受影响。" },
            { "ai.failed", "AI 未完成，核心功能不受影响。" },
            { "ai.empty_response", "AI 没有返回内容。" },
            { "ai.bad_request", "AI 请求内容无效。" },
            { "ai.key.local", "密钥只写入本机配置，不会写入日志。" },
            { "update.section", "软件更新" },
            { "update.current", "当前版本" },
            { "update.check", "检查更新" },
            { "update.checking", "正在检查更新…" },
            { "update.upToDate", "已是最新版本" },
            { "update.upToDate.body", "当前版本 {0} 已是最新版本。" },
            { "update.none.title", "尚未发布版本" },
            { "update.none", "GitHub 上还没有发布任何版本。" },
            { "update.available.short", "有新版本 {0}" },
            { "update.autostart", "启动时自动检查更新" },
            { "update.title.available", "有新版本可用" },
            { "update.body.available", "当前版本 {0}，最新版本 {1}。是否下载并更新？" },
            { "update.notes", "版本说明" },
            { "update.source", "来源" },
            { "update.file", "文件" },
            { "update.size", "大小" },
            { "update.size.unknown", "未知" },
            { "update.install", "下载并更新" },
            { "update.later", "稍后" },
            { "update.page", "打开下载页面" },
            { "update.ok", "好" },
            { "update.downloading.title", "正在下载更新" },
            { "update.downloading.body", "下载期间请保持网络连接，完成后会询问是否立即重启。" },
            { "update.downloading.status", "准备中…" },
            { "update.ready.title", "更新已就绪" },
            { "update.ready.body", "已下载 {0}。重启后即完成更新。" },
            { "update.restart.now", "立即重启" },
            { "update.restart.later", "稍后手动重启" },
            { "update.failed.title", "无法完成更新" },
            { "update.security", "更新文件仅从官方 GitHub Release 下载，连接使用 HTTPS，并比对来源白名单。" },
            { "update.prerelease", "预览版" },
            { "update.error.network", "无法连接 GitHub，请检查网络后重试。" },
            { "update.error.timeout", "连接超时，请稍后重试。" },
            { "update.error.badRelease", "版本信息格式无法解读，已中止。" },
            { "update.error.untrusted", "下载来源未通过安全检查，已中止。" },
            { "update.error.tooLarge", "更新文件超过大小上限，已中止。" },
            { "update.error.incomplete", "下载的文件不完整，已中止。" },
            { "update.error.size", "下载文件大小与版本信息不符，已中止。" },
            { "update.error.download", "下载更新失败。" },
            { "update.error.locate", "找不到当前程序位置。" },
            { "update.error.unsupportedPath", "程序路径含有不支持的字符，请改由下载页面更新。" },
            { "update.error.readonly", "程序所在文件夹无法写入，请改由下载页面更新。" },
            { "update.error.config", "版本来源设置无效。" },
            { "update.error.policy", "更新来源未通过白名单检查。" }
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "app.title", "Outlook Classifier" },
            { "nav.quadrants", "Outlook Mail" },
            { "nav.todo", "Follow-ups" },
            { "nav.settings", "Settings" },
            { "nav.sidebarToggle", "Show / hide sidebar" },
            { "scope.days", "Days" },
            { "action.scan", "Scan" },
            { "action.cancel", "Cancel" },
            { "action.reclassify", "Move to quadrant" },
            { "action.retry", "Retry" },
            { "action.addTodo", "Add follow-up" },
            { "action.openInOutlook", "Open in Outlook" },
            { "action.addTodoManual", "Add" },
            { "action.todoDone", "Done" },
            { "action.todoReopen", "Reopen" },
            { "action.todoDelete", "Delete" },
            { "filter.all", "All" },
            { "quadrant.q1", "Urgent + Important" },
            { "quadrant.q2", "Urgent" },
            { "quadrant.q3", "Important" },
            { "quadrant.q4", "Neither" },
            { "reason.title", "Why it is here" },
            { "reason.override.manual", "You set this quadrant" },
            { "reason.keyword.urgent", "Subject has urgent keyword" },
            { "reason.keyword.important", "Subject has important keyword" },
            { "reason.signal.meeting", "Meeting request" },
            { "reason.signal.unread", "Unread" },
            { "reason.signal.flag", "Flagged" },
            { "reason.signal.importance", "High importance" },
            { "reason.signal.vip", "VIP sender" },
            { "reason.signal.default", "No special signal" },
            { "empty.title", "No mail in this range" },
            { "empty.body", "Change the day range or run a scan." },
            { "empty.start", "Scan" },
            { "loading.scanning", "Scanning mail…" },
            { "error.title", "Something failed" },
            { "error.outlook.unavailable", "Outlook not detected. Open Outlook, then scan again." },
            { "error.outlook.not_detected", "Outlook not detected. Open Outlook, then scan again." },
            { "error.scan.failed", "Mail could not be read. Narrow the range and retry." },
            { "error.blank.prevented", "Blank screen prevented. Retry or open settings." },
            { "status.readonly", "Read-only: mail is never modified" },
            { "status.done", "Scan finished: {0} items" },
            { "status.cancelled", "Scan cancelled" },
            { "detail.subject", "Subject" },
            { "detail.from", "From" },
            { "detail.time", "Received" },
            { "detail.folder", "Folder" },
            { "pick.quadrant", "Pick quadrant" },
            { "todo.title", "Follow-ups" },
            { "todo.filter.open", "Open" },
            { "todo.filter.done", "Done" },
            { "todo.filter.all", "All" },
            { "todo.filter.label", "Follow-up status" },
            { "todo.toggleDone", "Mark done: {0}" },
            { "todo.toggleDone.help", "Tick or untick this follow-up row" },
            { "todo.empty.title", "No follow-ups" },
            { "todo.empty.body", "Add one from a mail item or type a title." },
            { "todo.add.hint", "Type a follow-up and press Enter" },
            { "todo.added", "Added to follow-ups" },
            { "todo.source", "From: {0}" },
            { "todo.detail.state", "Status" },
            { "todo.detail.quadrant", "Quadrant" },
            { "todo.detail.created", "Created" },
            { "todo.detail.updated", "Updated" },
            { "todo.detail.due", "Due" },
            { "todo.detail.note", "Note" },
            { "todo.detail.mailMissing", "This mail is outside the current scan, so only the follow-up's own details are shown." },
            { "todo.waiting", "Waiting {0} d" },
            { "todo.waiting.today", "Added today" },
            { "todo.overdue", "Overdue by {0} d" },
            { "todo.due.today", "Due today" },
            { "todo.due.in", "Due in {0} d" },
            { "todo.due.none", "No due date" },
            { "todo.action.openMail", "Open original" },
            { "todo.action.setDue", "Set due date" },
            { "todo.action.clearDue", "Clear due date" },
            { "todo.action.clearDone", "Clear completed" },
            { "todo.cleared", "Cleared {0} completed follow-up(s)" },
            { "todo.note.placeholder", "Add a note…" },
            { "todo.note.save", "Save note" },
            { "todo.note.saved", "Note saved" },
            { "todo.sort", "Sort" },
            { "todo.sort.waiting", "Longest waiting" },
            { "todo.sort.due", "Due date" },
            { "todo.sort.quadrant", "Quadrant" },
            { "todo.sort.updated", "Recently updated" },
            { "todo.sort.manual", "As added" },
            { "todo.clearDone.confirm", "Permanently delete {0} finished follow-ups? This cannot be undone." },
            { "settings.days", "Default scan days" },
            { "settings.scanScope", "Scans always exclude Deleted Items and Junk E-mail (with their subfolders)." },
            { "settings.autoRefresh", "Check for new mail" },
            { "settings.autoRefresh.off", "Off" },
            { "settings.autoRefresh.minutes", "{0} min" },
            { "auto.refresh.updated", "Refreshed automatically: {0} mail" },
            { "settings.language", "Language" },
            { "settings.urgentKeywords", "Urgent keywords (comma-separated)" },
            { "settings.importantKeywords", "Important keywords (comma-separated)" },
            { "settings.vip", "VIP senders (comma-separated)" },
            { "settings.save", "Save settings" },
            { "settings.saved", "Settings saved" },
            { "settings.language.needRestart", "Language changed. Restart to apply fully." },
            { "settings.restart.auto", "Restart now" },
            { "settings.restart.manual", "I'll restart later" },
            { "settings.restart.later", "Apply on next start" },
            { "settings.restart.title", "Apply language change" },
            { "privacy.title", "Privacy and data" },
            { "privacy.location", "Data location" },
            { "privacy.minimize", "Mail fields stay local; message bodies are not stored by default." },
            { "privacy.export", "Export local data" },
            { "privacy.exported", "Exported to: " },
            { "privacy.openFolder", "Open folder" },
            { "privacy.clear", "Clear local data" },
            { "privacy.clear.confirm", "Clear settings, follow-ups, and reclassify memory? This cannot be undone." },
            { "privacy.cleared", "Local data cleared" },
            { "privacy.ai.off", "AI is off (enhancement only; core classification works without it)" },
            { "restart.title", "Restart required" },
            { "restart.body", "Some settings apply fully after a restart." },
            { "restart.now", "Restart now" },
            { "restart.later", "Restart later" },
            { "restart.next", "Apply on next start" },
            { "auto.scan.start", "Auto-scanning with last settings…" },
            { "ai.title", "AI enhancement (optional)" },
            { "ai.providers", "AI providers" },
            { "ai.provider", "Provider" },
            { "ai.addProvider", "Add" },
            { "ai.removeProvider", "Remove" },
            { "ai.loadModels", "Load models" },
            { "ai.models", "Model" },
            { "ai.models.empty", "Enter URL and key, then load models" },
            { "ai.models.loaded", "Loaded {0} models" },
            { "ai.models.failed", "Could not load model list" },

            { "ai.enabled", "Enable AI" },
            { "ai.baseUrl", "Provider URL (OpenAI-compatible)" },
            { "ai.model", "Model" },
            { "ai.apiKey", "API key (stored locally only)" },
            { "ai.consent.title", "Confirm fields to send" },
            { "ai.consent.body", "Only these whitelist fields are sent. Message body is never included." },
            { "ai.consent.send", "Send" },
            { "ai.consent.cancel", "Cancel" },
            { "ai.action", "AI note" },
            { "ai.disabled", "AI is off. Core features still work." },
            { "ai.network_failed", "AI network failed. Core features still work." },
            { "ai.timeout", "AI timed out. Core features still work." },
            { "ai.failed", "AI did not complete. Core features still work." },
            { "ai.empty_response", "AI returned no content." },
            { "ai.bad_request", "AI request is invalid." },
            { "ai.key.local", "The key is written only to the local settings file and never to logs." },
            { "update.section", "Software update" },
            { "update.current", "Current version" },
            { "update.check", "Check for updates" },
            { "update.checking", "Checking for updates…" },
            { "update.upToDate", "You're up to date" },
            { "update.upToDate.body", "Version {0} is the latest release." },
            { "update.none.title", "No releases yet" },
            { "update.none", "No release has been published on GitHub yet." },
            { "update.available.short", "Version {0} is available" },
            { "update.autostart", "Check for updates at startup" },
            { "update.title.available", "A new version is available" },
            { "update.body.available", "You have {0}. The latest version is {1}. Download and install it now?" },
            { "update.notes", "Release notes" },
            { "update.source", "Source" },
            { "update.file", "File" },
            { "update.size", "Size" },
            { "update.size.unknown", "unknown" },
            { "update.install", "Download and install" },
            { "update.later", "Later" },
            { "update.page", "Open download page" },
            { "update.ok", "OK" },
            { "update.downloading.title", "Downloading the update" },
            { "update.downloading.body", "Keep the connection open. You will be asked whether to restart when it finishes." },
            { "update.downloading.status", "Preparing…" },
            { "update.ready.title", "Update ready" },
            { "update.ready.body", "{0} has been downloaded. Restarting completes the update." },
            { "update.restart.now", "Restart now" },
            { "update.restart.later", "I'll restart later" },
            { "update.failed.title", "Update could not be completed" },
            { "update.security", "Updates come only from the official GitHub release over HTTPS, and the download host is checked against an allowlist." },
            { "update.prerelease", "pre-release" },
            { "update.error.network", "Could not reach GitHub. Check your connection and try again." },
            { "update.error.timeout", "The connection timed out. Try again later." },
            { "update.error.badRelease", "The release information could not be read. Update stopped." },
            { "update.error.untrusted", "The download source failed the security check. Update stopped." },
            { "update.error.tooLarge", "The update file is larger than the allowed size. Update stopped." },
            { "update.error.incomplete", "The downloaded file is incomplete. Update stopped." },
            { "update.error.size", "The downloaded file does not match the published size. Update stopped." },
            { "update.error.download", "The update download failed." },
            { "update.error.locate", "The running program could not be located." },
            { "update.error.unsupportedPath", "The program path contains unsupported characters. Update from the download page instead." },
            { "update.error.readonly", "The program folder is not writable. Update from the download page instead." },
            { "update.error.config", "The update source is not configured." },
            { "update.error.policy", "The update source failed the allowlist check." }
        };
    }
}
